runtime: go116

main: app

service: default

includes:
- secret.yaml

handlers:

- url: /static
  static_dir: app/static
  secure: always

- url: /favicon.ico
  static_files: app/static/favicon.ico
  upload: app/static/favicon.ico
  secure: always

- url: /.*
  script: auto
  secure: always
